name: build

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - '5.8-buster'
          - '5.10-buster'
          - '5.18-buster'
          - '5.20-buster'
          - '5.26'
          - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: curl -sL https://cpanmin.us | perl - --installdeps .
      - name: Run tests
        run: perl Makefile.PL && make && make test
      - name: Install XS
        run: curl -sL https://cpanmin.us | perl - Text::CSV_XS@1.58
      - name: Run XS tests
        run: perl Makefile.PL && make && TEST_PERL_TEXT_CSV=2 make test
