name: build_mac

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@master
      - name: perl -V
        run: perl -V
      - name: Install dependencies with develop
        run: curl -sL https://cpanmin.us | perl - --installdeps .
      - name: Run Makefile.PL
        run: perl Makefile.PL
      - name: Run tests
        run: make && make test
